name: ammp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  editable: ^2.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets\tracks.json
    - assets\Revised-Engine-Price.json